# databricks_app.yaml
name: pdf
description: An application for chatting with AI about uploaded documents
version: 1.0.0

# Requirements
requirements:
  - streamlit==1.45.1
  - requests==2.31.0
  - PyMuPDF==1.26.1
  - langchain==0.3.26
  - databricks-langchain==0.5.1
  - mlflow[databricks]>=3.1.0
  - python-dotenv==1.1.0
  - sacrebleu
  - evaluate

command: [
  "streamlit",
  "run",
  "main.py"
]
