name: Deploy UI to Databricks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ vars.DATABRICKS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Databricks CLI (v2)
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        echo "$HOME/.databricks/bin" >> $GITHUB_PATH

    - name: Verify Databricks CLI
      run: databricks --version

    - name: Configure Databricks CLI
      run: |
        databricks configure --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN

    - name: Deploy App
      run: |
        # Example: Deploy notebooks to Databricks workspace
        databricks workspace import-dir . /Workspace/Shared/M12_LLMOps/nlp_rangers/app
        databricks apps deploy pdf --source-code-path /Workspace/Shared/M12_LLMOps/nlp_rangers/app
